# Copyright (C) UGA GINP  - All Rights Reserved
# Written by Didier DONSEZ, 2016-2023

FROM nodered/node-red
MAINTAINER CampusIoT didier.donsez@gmail.com

RUN npm install node-red-admin

# Add useful node-red nodes here
# https://flows.nodered.org/search?type=node

# RUN npm install node-red-dashboard
# RUN npm install node-red-contrib-web-worldmap
# RUN npm install node-red-node-geofence

# RUN npm install red-contrib-mobius-flow-thingsboard

# RUN  npm install openapi-red 

RUN npm install node-red-contrib-influxdb
# RUN npm install node-red-contrib-ttn 
# RUN npm install node-red-node-helium 

# RUN npm install node-red-node-mongodb
# RUN npm install node-red-contrib-postgresql 
# RUN npm install node-red-node-mysql 

# RUN  npm install node-red-contrib-telegrambot 
# RUN npm install node-red-contrib-pubnub
# RUN npm install node-red-contrib-ifttt

# https://flows.nodered.org/node/node-red-contrib-gpsd
# RUN npm install node-red-contrib-gpsd

# RUN npm install node-red-contrib-cayenne-mqtt-client
RUN npm install node-red-contrib-sms-free-mobile

# https://flows.nodered.org/node/node-red-node-swagger
# RUN npm install node-red-node-swagger

# https://flows.nodered.org/node/node-red-contrib-logstash
# RUN npm install node-red-contrib-logstash
# RUN npm install node-red-contrib-firebase
# RUN npm install node-red-contrib-couchdb
# RUN npm install node-red-contrib-kafka-node
# RUN npm install node-red-contrib-amqp
# RUN npm install node-red-contrib-json2csv

# https://flows.nodered.org/node/node-red-node-google
# RUN npm install node-red-node-google


#
#  Misc
#


# RUN npm install node-red-contrib-ads-b

# For Barcode and QRCode generator https://flows.nodered.org/node/node-red-contrib-image-tools
# RUN npm install node-red-contrib-image-tools

# OpenWeatherMap
# RUN npm install node-red-node-openweathermap
# * https://flows.nodered.org/search?term=OpenWeatherMap
# * https://flows.nodered.org/flow/2a93e0ace27bb71f3feb0238e383ab47
# * https://flows.nodered.org/node/node-red-contrib-ui-heatmap

# Dynamic Network Map
# * Dynamic Network Map