{
 "title": "Tekelek",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceName\""
   }
  ]
 },
 "panels": [
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "deviceName" },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 1 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "ullage",
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "alarm",
     "measurement": "data",
     "select": [
      [
       { "params": [ "alarm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "sonicrssi",
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 15 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 15 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 15 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 15 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "ullage",
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "alarm",
     "measurement": "data",
     "select": [
      [
       { "params": [ "alarm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "sonicrssi",
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  { "title": "$deviceName", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 29 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 29 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 29 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 29 },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 16, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 18, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 29 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 29 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "measurement": "status",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Ullage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 34 },
   "yaxes": [
    { "format": "lengthm" }
   ],
   "targets": [
    {
     "alias": "ullage",
     "measurement": "data",
     "select": [
      [
       { "params": [ "ullage" ], "type": "field" },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Alarm",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "alarm",
     "measurement": "data",
     "select": [
      [
       { "params": [ "alarm" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Sonic RSSI",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 34 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "sonicrssi",
     "measurement": "data",
     "select": [
      [
       { "params": [ "sonicrssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}