{
 "title": "Wyres",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "deviceName",
    "query": "SHOW TAG VALUES WITH KEY = \"deviceName\""
   }
  ]
 },
 "panels": [
  {
   "title": "$deviceName",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "deviceName",
   "targets": [
    {}
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "lux" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "light" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "temperature",
     "measurement": "data",
     "query": "SELECT mean(\"temperature\") FROM \"data\" WHERE (\"applicationName\" = 'SICONIA' AND \"devEUI\" = '4883c7df30051c1b') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "temperature_2" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "temperature",
     "measurement": "data",
     "select": [
      [
       { "params": [ "temperature" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    },
    {
     "alias": "dew point",
     "measurement": "data",
     "select": [
      [
       { "params": [ "dewpoint" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "yaxes": [
    { "format": "pressurehpa" }
   ],
   "targets": [
    {
     "alias": "pressure",
     "measurement": "data",
     "select": [
      [
       { "params": [ "pressure" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Light",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "lux" }
   ],
   "targets": [
    {
     "alias": "light",
     "measurement": "data",
     "select": [
      [
       { "params": [ "light" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "VCC",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "alias": "light",
     "measurement": "data",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "RSSI",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "rssi" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "fCnt",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "PER",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "query": "SELECT 1- spread(\"fCnt\") / count(\"fCnt\")  FROM \"data\" WHERE (\"deviceName\" =~ /^$deviceName$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "fCnt" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "DataRate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "dr" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Battery",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "battery" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  },
  {
   "title": "Redundancy",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "redundancy",
     "measurement": "data",
     "select": [
      [
       { "params": [ "redundancy" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "deviceName", "operator": "=~", "value": "/^$deviceName$/" }
     ]
    }
   ]
  }
 ]
}